【ID-2】フッタースタイル変更
akkie8/moodify-web pull request #4
Opened 2024-12-15 10:35 UTC by Risa2024

### 概要
- 文字の上下位置を入れ替え。
- 下線を追加。
- フッター背景色追加。

### 迷った点
- マージンの設定が適切か。
- 下線の色や太さがデザインに合っているか。
- フッターの背景色は適切か。

### 確認していただきたい点
- スタイル変更に関して、配色や余白、要素の配置などで違和感がないか確認をお願いします。
- 修正後のコードに無駄や冗長な記述がなどがないか、改善点があればご指摘ください。

###変更ブランチ
Feature/footer update#1

2024-12-17 05:48 UTC, akkie8 commented
## 気になった事

- 次回からReviewersに @akkie8 を追加して申請依頼を飛ばして下さい！（現在は私が自ら追加してしまいましたw）
- Assignees には自分のアカウントを指定して下さい！

2024-12-17 06:23 UTC, akkie8 requested changes
何点かコメントを追加しました！
調べながら、ゆっくりで良いので修正をお願いします〜！！！

2024-12-17 06:23 UTC, akkie8 commented on src/app/layout.tsx
> +          <footer className='p-8 mt-4 text-center text-gray-500  bg-gray-50 '>
MUST: `bg-gray-50`の後に半角のスペースがあるので、`yarn format`を実行して全体的なコードの整形をお願いします〜！！

2024-12-17 06:23 UTC, akkie8 commented on src/app/layout.tsx
> +            <div className='my-4 h-px bg-gray-200 w-[85%] mx-auto'></div>
IMO: 

- 区切り線を表現する場合は`hr`タグを使用する方が望ましいです！
- `w-[85%]`については、Tailwindの標準クラスである`w-10/12`（83.333%）や`w-11/12`（91.666%）のいずれかに変更することをお勧めします。

### なせTailwindの標準クラス？
Tailwindは事前にコンパイルされたクラスを使用し、標準クラス（w-10/12など）は事前にビルドされていますが、任意の値（`w-[85%]`）を使用すると、その都度新しいCSSが生成され、パフォーマンスに影響する為
なるべく標準クラスを使用するようにしましょう！！

2024-12-17 06:23 UTC, akkie8 commented on src/app/layout.tsx
> +          <footer className='p-8 mt-4 text-center text-gray-500  bg-gray-50 '>
FYI: 全体的にmt-4は使わないようにしています。

## なぜmtを使わないのか

- 要素間のスペーシングをmb（margin-bottom）で統一することで、上から下への自然なフローが作れます
- 各コンポーネントが「自分の下に対して」どれだけスペースを取るか、という責任を持つ形で統一したいので

### ではどのようにfooterのスペーシングを調整するのか？（mt）

- 独立したセクション（footer, headerなど）として扱え、内部のスペーシングをより柔軟にコントロールできます。例えばpy-4 px-6など


## まとめ

- 独立したセクション（サイズの大きい要素・またはコンポーネント）は内部のスペーシングに`padding`を指定
- セクションないの子要素に対しては、要素間のスペーシングを`mb`（margin-bottom）で統一する

2024-12-17 06:23 UTC, akkie8 commented on src/app/layout.tsx
> +          <footer className='p-8 mt-4 text-center text-gray-500  bg-gray-50 '>
MUST: text-gray-500の後ろも半角スペースが２つ入っているので統一しましょう！

2024-12-17 06:23 UTC, akkie8 commented on src/app/layout.tsx
> +            <p className='mb-2'>Moodify © 2025</p>
👍👍👍

2024-12-18 03:36 UTC, Risa2024 commented on src/app/layout.tsx
> +          <footer className='p-8 mt-4 text-center text-gray-500  bg-gray-50 '>
レビューありがとうございます！
半角スペースを削除し`yarn format`も実行しました

2024-12-18 04:22 UTC, Risa2024 commented on src/app/layout.tsx
> +            <div className='my-4 h-px bg-gray-200 w-[85%] mx-auto'></div>
ご指摘ありがとうございます！
上記変更いたしました。ご確認をお願いいたします！

2024-12-18 04:26 UTC, Risa2024 commented on src/app/layout.tsx
> +          <footer className='p-8 mt-4 text-center text-gray-500  bg-gray-50 '>
レビューいただきありがとうございます！
mtを削除しp-*のみで修正しました。

2024-12-18 04:27 UTC, Risa2024 commented on src/app/layout.tsx
> +            <p className='mb-2'>Moodify © 2025</p>
ありがとうございます！

2024-12-18 04:37 UTC, Risa2024 commented
上記修正いたしました！
lintとbuildも通しています。
お手隙の際、ご確認をお願いいたします！

2024-12-19 03:26 UTC, akkie8 approved these changes
実装お疲れ様でした〜🎉🎉
![LGTM](https://image.lgtmoon.dev/316222)

2024-12-19 04:12 UTC, merged